#!/bin/bash

echo "🔐 Secrets recibidos (por variables de entorno):"
echo "--------------------------------------------------------------"
echo "GOOGLE_CREDENTIALS (definido?)      : ${GOOGLE_APPLICATION_CREDENTIALS:+✅}"
echo "DB_NAME                             : $DB_NAME"
echo "DB_USER                             : $DB_USER"
echo "DB_PASSWORD (oculto)                : ${#DB_PASSWORD} caracteres"
echo "AWS_ACCESS_KEY_ID                   : ${AWS_ACCESS_KEY_ID:0:4}***"
echo "AWS_SECRET_ACCESS_KEY               : ${AWS_SECRET_ACCESS_KEY:0:4}***"
echo "AWS_REGION                          : $AWS_REGION"
echo "BUCKET_NAME                         : $BUCKET_NAME"
echo ""

echo "⚙️  Inputs recibidos del workflow:"
echo "--------------------------------------------------------------"
echo "account_id                          : $1"
echo "visit_id                            : $2"
echo "project                             : $3"
echo "instance_connection_name            : $4"
echo ""
